### PR TITLE
Add `preserve` option

### PR DESCRIPTION
**Pull request by MoOx**
Setting `preserve` to `true` will preserve  `calc()` in the output, so
that they can be used by supporting browsers.
Useful now that browsers are starting to implement vars (eg Firefox
31+) & it’s even better for debug to see real rules.

I’ve refactored the code a little bit to make it easier to use the
`preserve` in the main function (& also use rework-visit which
is more bullet proof) like rework-vars.

This should be a major update since now calc need to be called as a
function (like rework-vars for example) to be able to pass options. So
this should be tagged as 0.3 (or maybe it’s time to ship 1.0 :) ?)

I also quickly refactor tests to make it more understandable
(plugins.js near preserve.css was confusing imo).

I also add some error reporting like we have in rework-vars. Btw, maybe we can
expand the use of balanced-match to rewrite other parts of the plugin.

I hope it’s ok.

FWI, I did this since I’m more seeing rework-vars & rework-calc as
fallback than replacement.
See https://github.com/reworkcss/rework-vars/issues/28
https://github.com/reworkcss/rework-vars/issues/29 &
https://github.com/segmentio/myth/issues/64

### CODE REVIEW

**Comment by MoOx** [comment]
Who maintain this repo ? It seems I'm the only one watching it. I can take care of it but not sure to be able to publish something...

poke @joakimbeng @reworkcss/owners

**Comment by jonathanong** [comment]
take control!

**Comment by MoOx** [comment]
@jonathanong I'll need access to npm (be added as a user at least) right (my npm login is `moox`) ?

**Comment by jonathanong** [comment]
hmmm i don't have publishing rights either. added you to all the repos i ahve access to

**Comment by MoOx** [comment]
Thanks @jonathanong. It seems you are listed here https://www.npmjs.org/package/rework-calc
Anyway I'll wait for a response of @joakimbeng before doing anything.

**Comment by jonathanong** [comment]
god damn that's not the account i use. fuck you npm!

**Comment by necolas** [comment]
There's not really any benefit to preserving `calc()` in the output, because the browser has to perform exactly the same calculation that can be done ahead of time with the build tool.

**Comment by MoOx** [comment]
The idea is to keep custom properties in the dev tools. It's just the same thing as for rework-vars (see screenshot in the PR desc)

**Comment by necolas** [comment]
Surely they will be there if you've set rework-vars to `preserve`, because the use of calc with variables won't be resolved by this module. Plus this changes the API without enough benefit IMO. If you don't need IE8 support, you don't need this module (unless you want to resolve simple calc's ahead of time to  avoid the browser needing to).

**Comment by MoOx** [comment]
If I use rework-vars as a fallback (so fallback + custom) I want ... Oh wait...



Ok closing this immediatly. I'm so stupid.
I will still send another one to keep my work for error report.

**Comment by necolas** [comment]
There are some good consistency changes in this PR though :)

**Comment by MoOx** [comment]
I just copy your work @necolas. I'm not the smart guy here.

**Comment by joakimbeng** [comment]
Sorry for the late response, been traveling..
@jonathanong I've added the correct user as owner to `rework-calc` on npm now, it's the "jongleberry" account right?

**Comment by jonathanong** [comment]
yeah. seeing if i can just delete it or transfer or it or something. switching users on npm is a pain in the ass.

**Comment by MoOx** [comment]
Can someone add me as a owner on rework-calc so I can ship 1.0.0 ? I think it's time to (checkout latest commits) :)

**Comment by joakimbeng** [comment]
@MoOx there you go :)

**Comment by MoOx** [comment]
Great, thanks. v1.0.0 has been published !

**Pull request closed without merging**
